<?php
// Load the Dompdf library
require 'dompdf/autoload.inc.php';
use Dompdf\Dompdf;
use Dompdf\Options;

// Set the default timezone
date_default_timezone_set('Asia/Kolkata'); // Change to your timezone

// Database connection
include 'db.php';
session_start();

// Ensure the user is logged in
if (!isset($_SESSION['user_id'])) {
    header('Location: login.php');
    exit;
}

$user_id = $_SESSION['user_id'];
$month_year = $_GET['month'] ?? date('Y-m'); // Default to current month

// Fetch transactions for the selected month
$query = "SELECT type, category, amount, created_at 
          FROM expenses 
          WHERE user_id = ? 
          AND DATE_FORMAT(created_at, '%Y-%m') = ?;";
$stmt = $conn->prepare($query);
$stmt->bind_param("is", $user_id, $month_year);
$stmt->execute();
$result = $stmt->get_result();

$total_income = 0;
$total_expense = 0;
$transactions = [];

// Separate transactions into income and expense
while ($row = $result->fetch_assoc()) {
    $transactions[] = $row;
    if ($row['type'] === 'Income') {
        $total_income += $row['amount'];
    } else {
        $total_expense += $row['amount'];
    }
}

// Prepare HTML content for PDF
$html = '
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Expense Tracker Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { text-align: center; margin-bottom: 5px; }
        h3 { text-align: center; margin: 5px 0; }
        h2 { text-align: center; margin: 10px 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #000; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .footer { margin-top: 20px; text-align: center; font-size: small; }
    </style>
</head>
<body>
    <hr>
    <h1>EXPENSE TRACKER</h1>
    <h3>' . strtoupper(date('F Y', strtotime($month_year . '-01'))) . ' REPORT &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ' . date('d-m-Y | g:i A') . '</h3>
    <hr><br>    
    <h3>Transaction Details</h3><br>
    <table>
        <tr>
            <th>No.</th>
            <th>Type</th>
            <th>Category</th>
            <th>Amount</th>
            <th>Date</th>
        </tr>';

foreach ($transactions as $index => $transaction) {
    // Set row color based on transaction type
    $rowColor = ($transaction['type'] === 'Income') ? '#d4edda' : '#f8d7da'; // Light green for income, light red for expense

    $html .= '
    <tr style="background-color: ' . $rowColor . ';">
        <td>' . ($index + 1) . '</td>
        <td>' . htmlspecialchars($transaction['type']) . '</td>
        <td>' . htmlspecialchars($transaction['category']) . '</td>
        <td>' . number_format($transaction['amount'], 2) . '</td>
        <td>' . date('d-m-Y', strtotime($transaction['created_at'])) . '</td>
    </tr>';
}

$html .= '
    </table><br>

    <h3>Total Income: Rs.' . number_format($total_income, 2) . ' &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  Total Expense: Rs.' . number_format($total_expense, 2) . '</h3><br>';

// Conditional message with color coding
if ($total_expense > $total_income) {
    $difference = $total_expense - $total_income;
    // Create a box for the message
    $html .= '
    <div style="background-color: #f8d7da; border: 1px solid red; padding: 10px; margin-top: 20px; border-radius: 5px;">
        <h2 style="color: red; margin: 0;">Your Expense is more than Income</h2>
        <h3 style="color: red; margin: 5px 0 0 0;">Your Loss: Rs.' . number_format($difference, 2) . ' This Month</h3>
    </div>';
} elseif ($total_income > $total_expense) {
    $difference = $total_income - $total_expense;
    // Create a box for the message
    $html .= '
    <div style="background-color: #d4edda; border: 1px solid green; padding: 10px; margin-top: 20px; border-radius: 5px;">
        <h2 style="color: green; margin: 0;">Your Income is more than Expense</h2>
        <h3 style="color: green; margin: 5px 0 0 0;">You Save: Rs.' . number_format($difference, 2) . ' This Month</h3>
    </div>';
}

$html .= '
    <div class="footer">
       Generated by Expense Tracker &trade; ~ ' . date('Y') . '
    </div>
</body>
</html>';

// Instantiate Dompdf
$options = new Options();
$options->set('defaultFont', 'Helvetica');
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

// Output the PDF
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="Report-' . date('M-Y') . '.pdf"');
echo $dompdf->output();
exit;
?>
